name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and build the plugin
      - name: Set up SDKMAN!
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.6
          sdk install groovy 4.0.18
          sdk use gradle 8.6
          sdk use groovy 4.0.18

      - name: Build the plugin
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle build

      # Upload the build artifact to GitHub Releases
      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/intellij-reek-plugin-*.zip
          asset_name: intellij-reek-plugin-${{ github.ref_name }}.zip
          asset_content_type: application/zip

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Create a GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

